### ISSUE TITLE
KeyError: 'model.diffusion_model.middle_block.1.transformer_blocks.0.attn2'

### ISSUE THREAD

**Issue by coronet1127** [benkyoujouzu/stable-diffusion-webui-visualize-cross-attention-extension#3]
Traceback (most recent call last):
  File "C:\Users\coron\OneDrive\デスクトップ\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\coron\OneDrive\デスクトップ\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "C:\Users\coron\OneDrive\デスクトップ\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\coron\OneDrive\デスクトップ\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\coron\OneDrive\デスクトップ\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\coron\OneDrive\デスクトップ\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\coron\OneDrive\デスクトップ\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\stable-diffusion-webui-visualize-cross-attention-extension\scripts\vxa.py", line 50, in generate_vxa
    layer = hidden_layers[layer_name]
KeyError: 'model.diffusion_model.middle_block.1.transformer_blocks.0.attn2'

**Comment by Ev-Bro** [comment]
I get a similar error

```
Traceback (most recent call last):
  File "C:\Users\username\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\username\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\username\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\username\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\username\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\username\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\username\AUTOMATIC1111\stable-diffusion-webui\extensions\stable-diffusion-webui-visualize-cross-attention-extension\scripts\vxa.py", line 64, in generate_vxa
    model.apply_model(latent, t, emb)
  File "C:\Users\username\AUTOMATIC1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\username\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\Users\username\AUTOMATIC1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1331, in forward
    xc = torch.cat([x] + c_concat, dim=1)
TypeError: can only concatenate list (not "NoneType") to list

```
